// Curated Lucide icon names for domain icons (add more as needed)
export const ICON_OPTIONS = [
  'activity',
  'alarm-clock',
  'bike',
  'book',
  'book-open',
  'brain',
  'briefcase',
  'brush',
  'code-2',
  'coffee',
  'dumbbell',
  'flame',
  'gamepad-2',
  'globe',
  'guitar',
  'heart',
  'laptop',
  'layers',
  'leaf',
  'lightbulb',
  'mic',
  'moon',
  'music',
  'pencil',
  'running', // may not exist — fallback
  'scissors',
  'star',
  'sun',
  'target',
  'trophy',
  'tv',
  'users',
  'wallet',
  'zap',
] as const

export type IconOption = typeof ICON_OPTIONS[number]
